spring:
  data:
    mongodb:
      username: developer
      password: developer123
      host: ds137488.mlab.com
      port: 37488
      database: heroku_qh597p5f

messages:
  exception:
    loginInvalido: "Usuario ou senha incorreto"
    cpfExistente: "CPF ja possui cadastro"
    emailExistente: "Email ja possui cadastro"
    erroInterno: "Ocorreu um erro interno, entre em contato com nossos canais de atendimento"
    usuarioNaoEncontrado: "Impossivel realizar a troca, usuario nao encontrado!"
    pontuacaoInsuficiente: "Pontuacao atual insuficiente para realizar a troca"
  sucesso:
    pontuacao: "Pontuacoes registradas com sucesso"
  erro:
    pontuacao: "Pontuacoes registradas com falhas"
